class BankStatementPageLocators:

    CREDIT_CARD_RADIO_CSS = "[id='Credit Statement']"
    BANK_STATEMENT_RADIO_CSS = "[id='Bank Statement']"
    OP_TABLE_HEADER_XPATH = "//table[@id='bsTable']//thead//tr//th"
    OP_TABLE_BODY_XPATH = "//div[@class='Extraction-tables position-relative']//table[@id='bsTable']//tbody//tr"
    BANK_STATEMENT_DOWNLOAD_XPATH = "//button[contains(text(),'Download')]"
    MODULE_HISTORY_ALL_FILENAME_XPATH = "//div[@class='services-history-table-body-container']//div[@class='row-data']//div[starts-with(@class,'services-history-table-header-filename')]"
    MODULE_HISTORY_1ST_FILENAME_XPATH = "(//div[@class='services-history-table-body-container']//div[@class='row-data']//div[starts-with(@class,'services-history-table-header-filename')])[1]"
    MODULE_HISTORY_DATETIME_XPATH = "(//div[@class='services-history-table-body-container']//div[@class='row-data']//div[@class='services-history-table-header-dateAndTime'])[1]"
    FILESTATUS_PROCESSING_XPATH = "(//div[@class='services-history-table-body-container']//div[@class='row-data']//div[@data-testid='processing'])[1]"
    FILESTATUS_PARTIALLY_DONE_XPATH = "(//div[@class='services-history-table-body-container']//div[@class='row-data']//div[@data-testid='partially-done'])[1]"
    MODULE_HISTORY_HEADER_XPATH = "//div[@class='services-history-table-header fw-semibold']"
    MODULE_HISTORY_SEARCH_BAR_CSS = "[placeholder='Search By FileName']"
    SP_SEARCH_BAR_CSS = "[placeholder='Search File Name']"
    PAGE_SIZE_XPATH = "//select[contains(@class,'range-date-picker')]"
    SUPPORT_PORTAL_FILESTATUS = "(//table[@data-testid='support-portal-table']//tbody//td)[last()]"
    NO_OF_FILES_AF_SEARCHED = "(//table[@data-testid='support-portal-table']//tbody//tr[@data-testid='enabled'])"
    PROCEED_BTN_XPATH = "//button[contains(text(),'Proceed')]"
    SELECT_ALL_TXN_SUMMARY_DATA_XPATH = "(//table[@class='table table-striped']//thead)"
    BANK_NAME_INPUT_FIELD_CSS = "[name='BANK NAME']"
    BANK_ADDRESS_INPUT_FIELD_CSS = "[name='BANK ADDRESS']"
    ACC_NUM_INPUT_FIELD_CSS = "[name='ACCOUNT NUMBER']"
    ACC_TYPE_INPUT_FIELD_CSS = "[name='ACCOUNT TYPE']"
    CUSTOMER_NAME_INPUT_FIELD_CSS = "[name='CUSTOMER 1']"
    CUSTOMER_NAME2_INPUT_FIELD_CSS = "[name='CUSTOMER 2']"
    ACC_ADDRESS_INPUT_FIELD_CSS = "[name='ACCOUNT ADDRESS']"
    EDIT_ACCOUNT_BTN_XPATH = "(//div[@class='bank-statement-icons'])//div//span[1]"
    SAVE_BTN_XPATH = "//button[@type='submit' and text()='Save']"
    OUTPUT_METADATA_TAB_XPATH = "//div[text()='Metadata']"
    OUTPUT_TXN_TAB_XPATH = "//div[text()='Transactions']"
    OUTPUT_RECONCILIATION_TAB_XPATH = "//div[text()='Reconciliation']"
    SELECT_PAGE_NUMBER_CSS = "[name='PAGE_NUMBER']"
    TXN_DATE_INPUT_FIELD_CSS = "[name='TRANSACTION_DATE']"
    DESCRIPTION_INPUT_FIELD_CSS = "[name='DESCRIPTION']"
    CHECK_NO_INPUT_FIELD_CSS = "[name='CHECK_NUMBER']"
    DEBIT_INPUT_FIELD_CSS = "[name='DEBIT']"
    CREDIT_INPUT_FIELD_CSS = "[name='CREDIT']"
    BALANCE_INPUT_FIELD_CSS = "[name='BALANCE']"
    PREVIEW_ENABLED_1ST_BTN_XPATH = "(//div[@class='row-data']//div[@data-testid='preview-enabled'])[1]//span"
    RECONCILIATION_TAB_XPATH = "//div[@aria-label='Reconciliation']"
    RECONCILIATION_STATUS_XPATH = "((//table[@data-testid='reconciliation-table']//tbody//tr)[1]//td)[last()]"
    STATEMENT_TYPE_CSS = "[data-testid='statement-type-select']"
    ACCOUNT_NO_CSS = "[data-testid='account-select']"
    CASH_FLOW_DOWNLOAD_CSS = "[class='cashflow-download-icon']"
    CASH_FLOW_REPORT_TAB_CSS = "[id='justify-tab-example']"
    CASH_FLOW_ANALYSIS_TAB_CSS = "[id='justify-tab-example-tab-overAllCashFlow']"
    MONTHLY_CASH_FLOW_TAB_CSS = "[id='justify-tab-example-tab-monthlyCashFlow']"
    FORMULAE_TITLE_XPATH = "//h5[@class='metric-title']"
    CASH_FLOW_FORMULAE_NAME_XPATH = "//h5[text()='Cash Flow']/parent::div//button//div[@class='label']"
    TXN_PATTERN_FORMULAE_NAME_XPATH = "//h5[text()='Transaction Pattern']/parent::div//button//div[@class='label']"
    CASH_BUFFER_FORMULAE_NAME_XPATH = "//h5[text()='Cash Buffer']/parent::div//button//div[@class='label']"
    RISK_INDICATORS_FORMULAE_NAME_XPATH = "//h5[text()='Risk Indicators']/parent::div//button//div[@class='label']"
    SIMPLE_FORECASTING_FORMULAE_NAME_XPATH = "//h5[text()='Simple Forecasting']/parent::div//button//div[@class='label']"
    BUSINESS_LIQUIDITY_FORMULAE_NAME_XPATH = "//h5[text()='Business Liquidity']/parent::div//button//div[@class='label']"
    PERFORMANCE_METRICS_FORMULAE_NAME_XPATH = "//h5[text()='Performance Metrics']/parent::div//button//div[@class='label']"
    CATEGORIZATION_FORMULAE_NAME_XPATH = "//h5[text()='Categorization Report Matrix']/following-sibling::div//div//h2"
    INCOME_CLASSIFICATION_FORMULAE_NAME_XPATH = "//h2[text()='Income Classification']/following::div[1]//span[@class='card-title']"
    INCOME_INDICATORS_FORMULAE_NAME_XPATH = "//h2[text()='Income Indicators']/following::div[1]//span[@class='card-title']"
    INCOME_SUBCLASSIFICATION_FORMULAE_NAME_XPATH = "//h2[text()='Income Subclassification']/following::div[1]//span[@class='card-title']"
    CATEGORIZATION_RISK_INDICATORS_FORMULAE_NAME_XPATH = "//h2[text()='Risk Indicators']/following::div[1]//span[@class='card-title']"
    DEBT_MANAGEMENT_FORMULAE_NAME_XPATH = "//h2[text()='Debt Management']/following::div[1]//span[@class='card-title']"
    OPERATING_EXPENSES_FORMULAE_NAME_XPATH = "//h2[text()='Living/Operating Expenses']/following::div[1]//span[@class='card-title']"
    UTILITY_SERVICES_FORMULAE_NAME_XPATH = "//h2[text()='Utilities & Services']/following::div[1]//span[@class='card-title']"
    FINANCIAL_SERVICES_FORMULAE_NAME_XPATH = "//h2[text()='Financial Services']/following::div[1]//span[@class='card-title']"
    SHOPPING_DISCRETIONARY_FORMULAE_NAME_XPATH = "//h2[text()='Shopping & Discretionary']/following::div[1]//span[@class='card-title']"
    OTHER_CASH_FLOW_PATTERNS_FORMULAE_NAME_XPATH = "//h2[text()='Other Cash Flow Patterns']/following::div[1]//span[@class='card-title']"
    SAVING_PATTERN_FORMULAE_NAME_XPATH = "//h2[text()='Savings Patterns']/following::div[1]//span[@class='card-title']"
    OP_SCREEN_BACK_BTN_XPATH = "//*[name()='svg' and @data-icon='angle-left']/parent::button"
    OP_SCREEN_HISTORY_BTN_XPATH = "//*[name()='svg' and @data-icon='clock-rotate-left']/parent::button"
    REVIEW_TRANSACTIONS_BTN_XPATH = "//button[text()='Review Transactions']"
    OP_SCREEN_ANALYSIS_BTN_XPATH = "//button[text()='Analysis']"
    ANALYZE_POPUP_BTN_XPATH = "//button[text()='Analyze']"
    ACC_SUMMARY_CATEGORY_XPATH = "(//h5[text()='Account Summary Table']/following::table)[1]//tbody//tr//td[1]"
    INCOME_ANALYSIS_CATEGORY_XPATH = "(//h5[text()='Income Analysis']/following::table)[1]//tbody//tr//td[1]"
    INCOME_STABILITY_CATEGORY_XPATH = "(//h5[text()='Income Stability Assessment']/following::table)[1]//tbody//tr//td[1]"
    LOAN_DECISIONING_CATEGORY_XPATH = "(//h5[text()='Loan Decisioning Indicators']/following::table)[1]//tbody//tr//td[1]"
    DEBT_PAYMENTS_CATEGORY_XPATH = "(//h5[text()='Debt Payments']/following::table)[1]//tbody//tr//td[1]"
    MONTH_OVER_MONTH_CATEGORY_XPATH = "(//h5[text()='Month-over-Month Visualization Data']/following::table)[1]//tbody//tr//td[1]"
    CASH_FLOW_METRICS_CATEGORY_XPATH = "(//h5[text()='Cash Flow Metrics']/following::table)[1]//tbody//tr//td[1]"
    TXN_PATTERN_CATEGORY_XPATH = "(//h5[text()='Transaction Pattern Analysis']/following::table)[1]//tbody//tr//td[1]"
    DEBT_COUNTERPARTIES_CATEGORY_XPATH = "(//h5[text()='Debt Related Counterparties']/following::table)[1]//tbody//tr//td[1]"
    TOP_COUNTERPARTIES_CATEGORY_XPATH = "(//h5[text()='Top Counterparties']/following::table)[1]//tbody//tr//td[1]"
    PORTFOLIO_SECTION_XPATH = "//h1[text()='Portfolios']"
    FILE_DETAILS_SECTION_XPATH = "//h1[text()='FILE DETAILS']"
    CREATE_NEW_PORTFOLIO_BTN_XPATH = "//button[@class='create']"
    START_BTN_XPATH = "//button[text()='Start']"
    ADD_FILES_BTN_XPATH = "//button[text()='Add Files']"
    COMBINE_CASH_FLOW_SECTION_XPATH = "//h1[text()='Combined Cash flow']"
    PORTFOLIO_NAME_INPUT_CSS = "[id='portfolioName']"
    CREATE_PORTFOLIO_BTN_XPATH = "//div[text()='Create Portfolio']"
    FILE_UPLOAD_STATUS_XPATH = ""
    SELECTED_PORTFOLIO_NAME_XPATH = ""
    COMBINE_CASH_FLOW_CHECKBOX_XPATH = "[placeholder='Enable Combined Cashflow']"
    