class HomePageLocators:
    
    EXTRACTION_BTN_XPATH = "//span[text()='Extraction']"
    BANK_STMNT_XPATH = "//span[contains(text(),'Bank Statement')]"
    CASH_FLOW_XPATH = "//span[contains(text(),'Cash Flow Analysis')]"
    CON_AI_BTN_XPATH = "//span[contains(text(),'Conversational AI')]"
    RENT_ROLL_BTN_XPATH = "//span[contains(text(),'Rent Roll')]"
    PA_BTN_XPATH = "//span[contains(text(),'Predictive Analytics')]"
    REDACTION_BTN_XPATH = "//span[contains(text(),'Redaction')]"
    RECOGNITION_BTN_XPATH = "//span[contains(text(),'Recognition')]"
    CLASSIFICATION_BTN_XPATH = "//span[contains(text(),'Classification')]"
    DASHBOARD_BTN_XPATH = "//span[contains(text(),'Dashboard')]"
    UPLOAD_FILE_XPATH = "//input[@id='file']"
    NEXT_BTN_XPATH = "//button[@type='submit']"
    OUTPUT_FILE_XPATH = "//canvas[contains(@class,'canvas')]"
    IMG_OUTPUT_FILE_CSS = "[class='Outputscreen-imgViewer']>img"
    LEFT_SIDE_EXCEL_OUTPUT_FILE_XPATH = "//div[@class='excel_viewer']//table//tbody//tr[@row]"
    ERROR_OUTPUT_CSS = "[class='ErrorBoundaryBody']"
    SIDE_BAR_BTN_CSS = "[class='topbar-fabars']>button>svg"
    OUTPUT_EXCEL_DOWNLOAD_XPATH = "//img[@alt='XlsxFile']"
    OUTPUT_PDF_DOWNLOAD_XPATH = "//img[@alt='PdfFile']"
    OUTPUT_CSV_DOWNLOAD_XPATH = "//img[@alt='CsvFile']"
    OUTPUT_JSON_FILE_XPATH = "//img[@alt='JsonFile']"
    ERROR_MSG_XPATH = "//div[@role='alert']/descendant::span[@class='para']"
    SUBMIT_BTN_XPATH = "//button[contains(text(),'Submit')]"
    ERROR_OUTPUT_CSS2 = "[class='layout-card']>div>p>span"
    SELECT_PAGE_XPATH = "//div[@class='page_selection_body_select_pdf_page ']//div[@class='react-pdf__Page']"
    LAST_TAB_NAME_XPATH = "(//ul[@role='tablist']/descendant::button//span)[last()]"
    OUTPUT_TABLIST_NAME_XPATH = "//ul[@role='tablist']/descendant::button//span"
    UPLOAD_FILE_TAB_CSS = "[id='justify-tab-example-tab-Upload file']"
    HISTORY_TAB_CSS = "[id='justify-tab-example-tab-History']"
    DISCLAIMER_OKAY_XPATH = "//button[text()='Okay']"
    SUCCESS_MSG_XPATH = "//div[@role='alert']//span"